language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  
before_install:
 - curl -sS https://getcomposer.org/installer | php

before_script:
 - php composer.phar install --dev
 - php composer.phar dump

script:
 - (phpunit)
 
