language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
  
before_install:
 - curl -sS https://getcomposer.org/installer | php

before_script:
 - php composer.phar dump

script:
 - (cd tests ; phpunit)

